//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba2Parcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_persona
    {
        public int customerId { get; set; }
        public string customerName { get; set; }
        public string contactName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> postalCode { get; set; }
        public string country { get; set; }
    }
}
